version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - subvert

  node:
    image: node:alpine
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - app
    networks:
      - subvert

networks:
  subvert:
    driver: bridge